# run with --cap-add sys_admin --security-opt label=disable

ARG BASE_IMAGE=ghcr.io/kuubik-os/kuubik:latest
ARG INSTALL_IMAGE_PAYLOAD=ghcr.io/kuubik-os/kuubik:latest

FROM ${BASE_IMAGE}
ARG INSTALL_IMAGE_PAYLOAD
RUN --mount=type=bind,source=./.,target=/src \
    /src/build.sh
